export { Settings as SettingsIcon } from "./Settings";
export { Play as PlayIcon } from "./Play";
export { CodeCommit as CodeCommitIcon } from "./CodeCommit";
export { Success as SuccessIcon } from "./Success";
export { Failed as FailedIcon } from "./Failed";
export { Pending as PendingIcon } from "./Pending";
export { User as UserIcon } from "./User";
export { Calendar as CalendarIcon } from "./Calendar";
export { StopWatch as StopWatchIcon } from "./StopWatch";
